version: '3'

services:

    web:
        build: ./web
        expose: 
            - "3000"
        volumes:
            - "./web:/app"
        restart: unless-stopped

    proxy:
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - "proxy:/etc/nginx/conf.d"
        restart: unless-stopped

    db:
        image: mongo
        ports: 
            - "27017:27017"
        volumes:
            - "mongodb:/data/db"

volumes:
    proxy: 
    mongodb: 
