version: '3'

services:

    web:
        build: ./web
        expose: 
            - "3000"
        volumes:
            - "./web/src:/app/src"
        restart: unless-stopped
        networks:
            - default
    
    auth:
        build: ./authapi
        volumes:
            - "./authapi:/app"
        restart: unless-stopped
        ports:
            - "5005:3000"
        expose:
            - "3000"
        networks: 
            - default

    proxy:
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - "proxy:/etc/nginx/conf.d"
        restart: unless-stopped
        networks:
            - default

    db:
        image: mongo
        expose: 
            - "27017"
        volumes:
            - "mongodb:/data/db"
        networks:
            - default

volumes:
    proxy: 
    mongodb: 

networks:
    default:
        driver: bridge
