version: '3'

services:

    web:
        build: ./web
        expose: 
            - "3000"
        volumes:
            - ./web/src:/app/src
        restart: unless-stopped
        environment: 
            - MONGODB=db:27017
        networks:
            - default

    proxy:
        build: ./nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - web-root:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - ./dhparam:/etc/ssl/certs
        restart: unless-stopped
        networks:
            - default

    db:
        image: mongo
        expose: 
            - "27017"
        volumes:
            - "mongodb:/data/db"
            - "./db/create-root.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
        environment: 
            - MONGO_INITDB_DATABASE=amydb
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpwd2020
        networks:
            - default

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
        depends_on:
        - proxy
        command: certonly --webroot --webroot-path=/var/www/html --email webmaster@uec.org.au --agree-tos --no-eff-email --force-renewal -d uec.org.au  -d www.uec.org.au

volumes:
    mongodb:
    web-root:
    certbot-etc:
    certbot-var: 

networks:
    default:
        driver: bridge
