version: '3'

services:

    web:
        build: ./web
        expose: 
            - "3000"
        volumes:
            - "./web/src:/app/src"
        restart: unless-stopped
        environment: 
            - MONGODB=db:27017
        networks:
            - default

    proxy:
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - "proxy:/etc/nginx/conf.d"
        restart: unless-stopped
        networks:
            - default

    db:
        image: mongo
        expose: 
            - "27017"
        ports:
            - "27017:27017"
        volumes:
            - "mongodb:/data/db"
        networks:
            - default

volumes:
    proxy: 
    mongodb: 

networks:
    default:
        driver: bridge
